# Generated by Django 2.1.2 on 2018-10-27 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.EmailField(max_length=23)),
                ('rut', models.CharField(max_length=11)),
                ('NombreCompleto', models.CharField(max_length=30)),
                ('Fecha_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('numero', models.IntegerField()),
                ('region', models.CharField(max_length=30)),
                ('Comuna', models.CharField(max_length=30)),
                ('Vivienda', models.CharField(max_length=20)),
            ],
        ),
    ]
