# Generated by Django 2.1.2 on 2018-10-29 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_perritos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perritos',
        ),
        migrations.AddField(
            model_name='postulantes',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
