# Generated by Django 2.1.2 on 2018-11-13 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181028_2342'),
        ('blog', '0002_registro'),
        ('blog', '0002_auto_20181027_1902'),
    ]

    operations = [
    ]
