# Generated by Django 2.1.2 on 2018-10-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perritos',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
    ]
