# Generated by Django 2.1.2 on 2018-10-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20181028_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='perritos',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
