# Generated by Django 2.1.2 on 2018-11-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_perritos_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perritos',
            name='author',
        ),
    ]
